spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username:
    password:
    driverClassName: org.h2.Driver
  jpa:
    #spring.jpa.hibernate.ddl-auto=update
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true

server:
  error:
    include-binding-errors: always
    include-message: always

